{
 "title": "Parking Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{swarm_service=\"services_parking\"}"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "StatisticsController GET /user/statistics/{uid}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"GET\", uri=\"/user/statistics/{uid}\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\", uri=\"/statistics\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "PlaceController GET /place/free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"GET\", uri=\"/place/free\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\", uri=\"/place/free\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "PlaceController POST /place/unbook/{id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{uri=\"/place/unbook/{id}\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\", uri=\"/place/unbook/{id}\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "PlaceController POST /place/book",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"POST\", uri=\"/place/book\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\", uri=\"/place/book\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  { "title": "Errors number", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Number of 5xx responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{ status=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}